apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: automagic
  name: automagic
  namespace: piap
spec:
  type: NodePort
  selector:
    io.kompose.service: automagic
  ports:
    - name: "automagic"
      port: 9200
      targetPort: 8080
      nodePort: 30200
status:
  loadBalancer: {}
