apiVersion: v1
kind: Service
metadata:
  name: caldera-victim
  namespace: piap
  labels:
    app: caldera-victim
spec:
  type: ClusterIP
  selector:
    app: caldera-victim
  clusterIP: None
