apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector
  namespace: piap
  labels:
    io.kompose.service: connector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: connector
  template:
    metadata:
      labels:
        io.kompose.service: connector
    spec:
      containers:
      - name: connector
        image: ciscosecure/resource-connector:latest
        env:
        - name: CONNECTOR_NAME
          valueFrom:
            secretKeyRef:
              name: connector-creds
              key: connector-name
        - name: CONNECTOR_KEY
          valueFrom:
            secretKeyRef:
              name: connector-creds
              key: connector-key
        - name: TZ
          value: Europe/Berlin
        volumeMounts:
        - name: connector-data
          mountPath: /data
      volumes:
      - name: connector-data
        hostPath:
          path: /opt/connector-data
          type: DirectoryOrCreate