apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: dashy
  name: dashy
  namespace: piap
spec:
  type: NodePort
  selector:
    io.kompose.service: dashy
  ports:
    - name: "dashy"
      port: 9100
      targetPort: 8080
      nodePort: 30100
status:
  loadBalancer: {}
