apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: dashy
  name: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dashy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/piap-kind-komp-cisco-pod-network: "true"
        io.kompose.service: dashy
    spec:
      containers:
        - image: ghcr.io/lissy93/dashy:latest
          name: dashy
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /user-data/conf.yml
              name: dashy-config.yml
      restartPolicy: Always
      volumes:
        - name: dashy-config
          host-Path: 
            path: ./dashy/dashy-conf.yml
status: {}
