apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: dashy
  name: dashy
spec:
  type: NodePort
  selector:
    app: dashy
  ports:
    - name: "9000"
      port: 9000
      targetPort: 8080
      nodePort: 9000
status:
  loadBalancer: {}
