apiVersion: v1
kind: Service
metadata:
  name: ig-mcp
  namespace: piap
  labels:
    app: ig-mcp
spec:
  type: NodePort
  selector:
    app: ig-mcp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30060
      protocol: TCP
