apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/piap-kind-komp-cisco-pod-network: "true"
        io.kompose.service: nginx
        app: nginx
    spec:
      initContainers:
        - name: copy-files
          image: busybox
          command: ['sh', '-c', 'cp /source/nginx.conf /config/ && cp /source/index.html /www/']
          volumeMounts:
            - name: source-files
              mountPath: /source
            - name: nginx-config
              mountPath: /config
            - name: nginx-www
              mountPath: /www
      containers:
        - image: nginx:alpine
          name: nginx-web
          env:
            - name: TZ
              value: Europe/Berlin
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-www
              mountPath: /usr/share/nginx/html
      restartPolicy: Always
      volumes:
        - name: source-files
          hostPath:
            path: /web
            type: Directory
        - name: nginx-config
          emptyDir: {}
        - name: nginx-www
          emptyDir: {}
status: {}
