apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/piap-kind-komp-cisco-pod-network: "true"
        io.kompose.service: nginx
        app: nginx
    spec:
      containers:
        - image: nginx:alpine
          name: nginx-web
          env:
            - name: TZ
              value: Europe/Berlin
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: web-files
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: web-files
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      restartPolicy: Always
      volumes:
        - name: web-files
          hostPath:
            path: /web
            type: Directory
status: {}
