apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/piap-kind-komp-cisco-pod-network: "true"
        io.kompose.service: nginx
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Berlin
          image: lscr.io/linuxserver/nginx:latest
          name: nginx-web
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: nginx-conf
              mountPath: /config/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-html
              mountPath: /config/www/index.html
              subPath: index.html
      restartPolicy: Always
      volumes:
        - name: nginx-conf
          hostPath:
            path: /web/nginx.conf
            type: FileOrCreate
        - name: nginx-html
          hostPath:
            path: /web/index.html
            type: FileOrCreate
status: {}
