apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
  namespace: piap
spec:
  type: NodePort
  selector:
    io.kompose.service: nginx
  ports:
    - name: "nginx"
      port: 9400
      targetPort: 80
      nodePort: 30400
status:
  loadBalancer: {}
