apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: piap
data:
  default.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        # Enable server-side includes so we can inject $remote_addr into the page
        ssi on;
        ssi_silent_errors on;
    }
