apiVersion: v1
kind: Service
metadata:
  name: playwright-mcp
  namespace: piap
  labels:
    app: playwright-mcp
spec:
  type: NodePort
  selector:
    app: playwright-mcp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30070
      protocol: TCP
