apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: playbook
  name: playbook
  namespace: piap
spec:
  type: NodePort
  selector:
    io.kompose.service: playbook
  ports:
    - name: "playbook"
      port: 9250
      targetPort: 80
      nodePort: 30250
status:
  loadBalancer: {}
