apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: rdp-server
  name: rdp-server
  namespace: piap
spec:
  type: NodePort
  selector:
    io.kompose.service: rdp-server
  ports:
    - name: "rdp"
      port: 3389
      targetPort: 3389
      nodePort: 30389
status:
  loadBalancer: {}
