apiVersion: v1
kind: Service
metadata:
  name: saml-app
  namespace: piap
  labels:
    app: saml-app
spec:
  type: NodePort
  selector:
    app: saml-app
  ports:
    - name: "saml-app"
      port: 9400
      targetPort: 9400
      nodePort: 30400
