apiVersion: v1
kind: Service
metadata:
  name: splunk
  namespace: piap
spec:
  type: NodePort
  selector:
    app: splunk
  ports:
  - name: web
    port: 8000
    targetPort: 8000
    nodePort: 30500
    protocol: TCP
  - name: hec
    port: 8088
    targetPort: 8088
    nodePort: 30501
    protocol: TCP
  - name: splunkd
    port: 8089
    targetPort: 8089
    nodePort: 30502
    protocol: TCP
  - name: kvstore
    port: 8191
    targetPort: 8191
    # No nodePort - only accessible within cluster
    protocol: TCP