apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sse-check
  name: sse-check
  namespace: piap
spec:
  type: NodePort
  selector:
    io.kompose.service: sse-check
  ports:
    - name: "sse-check"
      port: 9550
      targetPort: 80
      nodePort: 30550
status:
  loadBalancer: {}
