apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: testcases
  name: testcases
  namespace: piap
spec:
  type: NodePort
  selector:
    io.kompose.service: testcases
  ports:
    - name: "testcases"
      port: 9250
      targetPort: 80
      nodePort: 30250
status:
  loadBalancer: {}
