apiVersion: v1
kind: Service
metadata:
  name: unittcms
  namespace: piap
  labels:
    app: unittcms
spec:
  type: NodePort
  selector:
    app: unittcms
  ports:
    - name: unittcms
      port: 9300
      targetPort: 8000
      nodePort: 30300
