apiVersion: v1
kind: Service
metadata:
  labels:
    app: uptime-kuma
  name: uptime-kuma
  namespace: piap
spec:
  type: NodePort
  selector:
    app: uptime-kuma
  ports:
    - name: "uptime-kuma"
      port: 3001
      targetPort: 3001
      nodePort: 30300
status:
  loadBalancer: {}
