kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 9000
    hostPort: 9000
  - containerPort: 8090
    hostPort: 8090
  - containerPort: 8200
    hostPort: 8200
  - containerPort: 2222
    hostPort: 2222
  - containerPort: 7010
    hostPort: 7010
  - containerPort: 3389
    hostPort: 3389
  - containerPort: 9100
    hostPort: 9100
  extraMounts:
  - hostPath: ./automagic-server
    containerPath: /automagic-server
  - hostPath: ./kanboard
    containerPath: /kanboard
  - hostPath: ./dashy
    containerPath: /dashy
  - hostPath: ./web
    containerPath: /web