events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        # Enable server-side includes so we can inject $remote_addr into the page
        ssi on;
        ssi_silent_errors on;
    }
}
